# Generated by Django 5.2.9 on 2025-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'directores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('texto_apertura', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pelicula_director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pelicula_personaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaPlaneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pelicula_planeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'pelicula_productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'planetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='system', max_length=150)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'productores',
                'managed': False,
            },
        ),
    ]
