# Generated by Django 5.2.9 on 2025-12-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peliculadirector',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peliculapersonaje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peliculaplaneta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peliculaproductor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personaje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planeta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productor',
            options={},
        ),
    ]
