# Generated by Django 5.2.9 on 2025-12-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0002_alter_director_options_alter_pelicula_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peliculadirector',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peliculapersonaje',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peliculaplaneta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peliculaproductor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personaje',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planeta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productor',
            options={'managed': False},
        ),
    ]
